config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])

	rescue ActiveRecord::RecordNotFound
		flash[:error] = "Could not find the post you were looking for."
		redirect_to posts_path
	end	

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
		redirect_to posts_path
	end	

	def create
		@post = Post.create(post_params)
		redirect_to posts_path
	end

	def edit
		@post = Post.find(params[:id])
	end	

	private
	def post_params
		params.require(:post).permit(:title, :author, :content)
	end	
end	

# @post = Post.edit(post_params)
# redirect_to edit_posts_path

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homework6</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error] || flash[:notice] %>
	<div id="flash">
		<% if flash[:error] %>
			<div id="flash-error"><%= flash[:error] %></div>
		<% end %>
		<% if flash[:notice] %>
			<div id="flash-notice"><%= flash[:notice] %></div>
		<% end %>
	</div>
<% end %>	

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1> Edit A Post </h1>

<%= form_for @post do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<br/>
	<%= f.label :author %>
	<%= f.text_field :author %>
	<br/>
	<%= f.label :content %>
	<%= f.text_field :content %>
	<br/>
	<%= f.submit :Update %>
<% end %>

app/views/posts/index.html.erb
<h1> All Posts </h1>

<ul>
	<% @posts.each do |post| %>
	<li> <strong> <%= link_to(post.title, post_path(post)) %> </strong> <br/> <em> <%= post.author %> </em> <br> <%= post.content %> <br> <br> </li>
<% end %>	
</ul>	

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

<%= form_for @post do |f| %>

	<%= f.label :title %>
	<%= f.text_field :title %>
	<br/>
	<%= f.label :author %>
	<%= f.text_field :author %>
	<br/>
	<%= f.label :content %>
	<%= f.text_field :content %>
	<br/>
	<%= f.submit :Create %>
<% end %>	

app/views/posts/show.html.erb
<h1> <strong> <%= @post.title %> </strong> </h1>
<h4> By: <em> <%= @post.author %> </em> </h4>
<p> <%= @post.content %> </p>
	